# -*- coding: utf-8 -*-
"""regressao_logistica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcnY_vnGokeC4D8lIulgpQ-023Gdf_Tk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import kagglehub

path = kagglehub.dataset_download("yasserh/titanic-dataset")

df = pd.read_csv("/kaggle/input/titanic-dataset/Titanic-Dataset.csv")

df.head()

df = df.drop(["Name", "Ticket", "Cabin", "PassengerId", "Embarked"], axis=1)

df["Sex"] = df["Sex"].map({"male":0, "female": 1})

df.isnull().sum()

df['Age'] = df['Age'].fillna(df['Age'].mean())

X = df.drop("Survived", axis=1)
y = df["Survived"]

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X,y)

predict = model.predict(X)
predict_prob = model.predict_proba(X)[:,1]

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:", accuracy_score(y, predict))
print("Precision:", precision_score(y, predict))
print("Recall:", recall_score(y, predict))
print("F1:", f1_score(y, predict))