# -*- coding: utf-8 -*-
"""Regressao_de_Ridge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYDsHebrfi-XWjNJkw9EfHqife2q-mgT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import Ridge

from sklearn.datasets import load_diabetes
df = load_diabetes()

X = df.data
y = df.target

model = Ridge(alpha=0.001)
model.fit(X, y)

predict = model.predict(X)

from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y, predict)
mse = mean_squared_error(y, predict)

print(mae)
print(mse)

plt.figure(figsize=(5,5))
plt.plot(y[:10], 'o')
plt.plot(predict[:10], 'x')
plt.legend(["y", 'predict'])
plt.title(f"MSE: {mse}")
plt.show()
