# -*- coding: utf-8 -*-
"""regressao_linear_simples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZZVxFNtnsgntrxGEqzkKgJo_PE2viGV
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from matplotlib import pyplot as plt

url = "https://www.statlearning.com/s/Advertising.csv"
df = pd.read_csv(url)

print(df.columns)
df = df.drop("Unnamed: 0", axis=1)

print(np.isnan(df).sum())

print(np.isinf(df).sum())

X = df.drop("sales", axis=1)
y = df["sales"]

print(X)
print(y)

model = LinearRegression()
model.fit(X,y)

predict = model.predict(X)
# print(y)
# print(predict)

plt.figure(figsize=(4, 4))
plt.plot(y[:10], "o")
plt.plot(predict[:10], "x")
plt.show()

from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y, predict)
mse = mean_squared_error(y, predict)

print(mae)
print(mse)